# Generated by Django 4.2.1 on 2023-06-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=100)),
                ('Company_logo', models.FileField(blank=True, null=True, upload_to='')),
                ('Company_city', models.CharField(max_length=100)),
            ],
        ),
    ]
